version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:16.0.0-browsers
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm run package
          command: npm run package
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
