version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
executors:
  default:
    working_directory: ~/project
    docker:
      - image: circleci/node:9.7.1-browsers
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm run package
          command: npm run package
workflows:
  build_and_deploy:
    jobs:
      - build
